esp8266:
  board: esp01_1m

packages:
  wifi: !include
    file: include/wifi.yaml
  relay: !include 
    file: include/single-relay.yaml
    vars: 
      relay_0_pin: "GPIO2"

# "All Device" baseline stuff here

<<: !include 
  file: include/esp8266-device-baseline.yaml
  vars:
    device_name: "805-esphome-lava-lamp"
    device_comment: "esp8266 ESP-01 with relay built into lava lamp cord."


