esp32:
  board: nodemcu-32s

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wifi: !include
    file: include/wifi.yaml
  relay: !include 
    file: include/single-relay.yaml
    vars: 
      relay_0_pin: "GPIO4"

# "All Device" baseline stuff here

<<: !include 
  file: include/device-baseline.yaml
  vars:
    device_name: "902-esphome"
    device_comment: "Single relay controlled by Board 902 connected on wifi."
