esp32:
# this is from the LilyGo github project:
# https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/blob/master/platformio.ini
  board: esp32s3box

packages:
  wifi: !include  
    file: include/wifi.yaml
  radar_motion: !include
    file: include/HLK-LD2420-radar-motion.yaml
    vars:
      # UART 1
      uart_2_tx_pin: "GPIO17"
      uart_2_rx_pin: "GPIO18"
  i2c: !include
    file: include/i2c.yaml
    vars:
      i2c_sda_pin: "GPIO47"
      i2c_scl_pin: "GPIO48"
  light_temp_humidity: !include
    file: include/light-temp-humidity.yaml
    vars:
      illuminance_pin: "GPIO3"
  buttons: !include
    file: include/buttons.yaml
    vars:
      button_0_pin: "GPIO8"
      button_1_pin: "GPIO19"
  relay: !include
    file: include/single-relay.yaml
    vars:
      relay_0_pin: "GPIO4"
  display: !include
    file: include/display.yaml

# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_name: "905-esphome"
    device_comment: "Full sensor array with wifi on board 905."


