esp32:
# this is from the LilyGo github project:
# https://github.com/Xinyuan-LilyGO/LilyGO-T-ETH-Series/blob/master/platformio.ini
  board: esp32s3box

packages:
  wifi: !include  
    file: include/wifi.yaml

# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_name: "905-esphome"
    device_comment: "Basic wifi on board 905."


