esp32:
  # esp32-WROOM-32*
  board: nodemcu-32s

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wifi: !include  
    file: include/wifi.yaml
  relay: !include
    file: include/single-relay.yaml
    vars:
      relay_0_pin: "GPIO13"
      invert_relay_0_pin: "true"

# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_name: "906-a-b-stereo-switch"
    device_comment: "A-B selector for stereo speaker input."

