esp8266:
  board: esp01_1m

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wifi: !include
    file: include/wifi.yaml

# "All Device" baseline stuff here

<<: !include 
  file: include/esp8266-device-baseline.yaml
  vars:
    device_hostname: "911-esphome"
    device_comment: "Board 911 controlling a transistor to remote power on/off Linda's BOSE speaker."

switch:
  - platform: gpio
    pin: GPIO03
    id: relay_0_id
    name: "Remote Power On/Off"
    icon: "mdi:power"
    on_turn_on:
    - delay: 100ms
    - switch.turn_off: relay_0_id