esp32:
  board: lolin_s2_mini
  variant: ESP32S2

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO15"
  wired_ethernet: !include
    file: include/wired-ethernet.yaml
    vars:
      ethernet_clk_pin: "GPIO34"  
      ethernet_mosi_pin: "GPIO36" 
      ethernet_miso_pin: "GPIO11" 
      ethernet_cs_pin: "GPIO21" 
      ethernet_interrupt_pin: "GPIO16" 
      ethernet_reset_pin: "GPIO9"
  illuminance: !include
    file: include/TEMT6000-illuminance.yaml
    vars:
      illuminance_pin: "GPIO14"
  radar_motion: !include
    file: include/HLK-LD2420-radar-motion.yaml
    vars:
      # Espressif docs say 17 and 18 are UART1 TXD and RXD
      uart_2_tx_pin: "GPIO17"
      uart_2_rx_pin: "GPIO18"
  i2c: !include
    file: include/i2c.yaml
    vars:
      i2c_sda_pin: "GPIO33"
      i2c_scl_pin: "GPIO35"
      # past 200kHz, this board fails to read the BMP and AHT sensors, failing with a 
      # "bad chip ID" error. I believe that error message really means "could not read chip ID,"
      # as dropping the freq <= 200kHz works.
      i2c_freq: "200kHz"
  temp_humidity: !include
    file: include/BMP280-AHT20-temp-humidity.yaml
  buttons: !include
    file: include/buttons.yaml
    vars:
      button_0_pin: "GPIO38"
      button_1_pin: "GPIO37"
  relay: !include
    file: include/single-relay.yaml
    vars:
      relay_0_pin: "GPIO13"

  # An empty display lamba routine still takes 60ms to execute on this board. That causes 
  # esphome to log continual warnings that the display component is taking too long.
  # Conclusion: this board does not have the horsepower to run all the sensors, the 
  # wired eithernet, the baseline components *AND* a display. So we drop the display.
#  display: !include
#    file: include/SDD1306-OLED-display-slow-boards.yaml

# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_name: "916-esphome"
    device_comment: "Full Sensor array on board 916."

