esp32:
  board: wemos_d1_mini32

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wired_ethernet: !include
    file: include/wired-ethernet.yaml
    vars:
      ethernet_clk_pin: "GPIO18"  
      ethernet_mosi_pin: "GPIO23" 
      ethernet_miso_pin: "GPIO19" 
      ethernet_cs_pin: "GPIO5" 
      ethernet_interrupt_pin: "GPIO26" 
      ethernet_reset_pin: "GPIO17"

sensor:
  - platform: adc
    pin: GPIO34
    name: "Photoresistor 0"
    id: photo_0_id
    attenuation: auto
    update_interval: 60s
    filters:
      - delta: 5.0
    #   - multiply: 3.3
    #   - lambda: |-
    #       return (x / 10000.0) * 2000000.0;
  - platform: adc
    pin: GPIO35
    name: "Photoresistor 1"
    id: photo_1_id
    attenuation: auto
    update_interval: 60s
    filters:
      - delta: 5.0





# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_name: "924-esphome"
    device_comment: "Wired baseline for board."
