esp32:
  board: esp32dev

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO33"
  wifi: !include  
    file: include/wifi.yaml


# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_hostname: "925-esphome"
    device_comment: "Baseline for board."

