# hardware wired up for this configuration:
# https://devices.esphome.io/devices/temt6000
# https://community.home-assistant.io/t/aht20-bmp280-combined-sensor/366411
# https://wiki.dfrobot.com/SKU_SEN0557_24GHz_Human_Presence_Sensing_Module
# https://wiki.seeedstudio.com/Grove-Relay/

esphome:
  name: esp32c3-multisensor-mk3
  friendly_name: arkadiahome multisensor, Mk III 
  comment: |- 
    temp, humidity, mm wave radar presence, light level, two momentary buttons, display
  area: Gym
  name_add_mac_suffix: true
  project:
    name: "arkadiahouse.home_automation"
    version: "0.1.1"

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

logger:

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  id: wifi_id
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esp32C3-test Fallback Hotspot"
    password: "PJnNb7VRCS3I"

captive_portal:

web_server:

time:
  - platform: homeassistant
    id: time_id

font:
  - file: "fonts/spleen-5x8.bdf"
    id: spleen_font
  - file: "fonts/LibreFranklin-Medium.ttf"
    id: temperature_large_font
    size: 48
  - file: "fonts/LibreFranklin-Medium.ttf"
    id: temperature_small_font
    size: 24

image:
  # - file: "images/presence-detected-icon.png"
  #   id: presence_detected_icon_id
  #   type: BINARY
  # - file: "images/no-presence-detected-icon.png"
  #   id: no_presence_detected_icon_id
  #   type: BINARY
  - file: "images/person-standing-still-icon.png"
    id: standing_still_icon_id
    type: BINARY

animation:
  - file: "images/falling-head.gif"
    id: motion_detected_animation_id
    type: BINARY

i2c:
  sda: GPIO6
  scl: GPIO7
  # goose up the frequency so that we don't get runtime warnings about the display component
  # taking too long to update.
  frequency: 300kHz

display:
  - platform: ssd1306_i2c
    model: "SSD1306_128x64"
    update_interval: 0.5s
    contrast: 20%
    invert: false
    lambda: |-
      auto width = it.get_width();
      auto height = it.get_height();

      // en lieu of a hardware blinky light, toggle a software light every time the display is updated
      static bool blinky_is_lit = false;
      blinky_is_lit = !blinky_is_lit;
      it.filled_rectangle(0, 12, 2, 2, blinky_is_lit ? COLOR_ON : COLOR_OFF);

      auto font_id = id(spleen_font);
      auto wifi_component = id(wifi_id);
      int char_height = 8;
      int line = 0;
      it.printf(0, ++line * char_height, font_id, TextAlign::BASELINE_LEFT, "%s", App.get_name().c_str());
      for (auto &ip : wifi_component->get_ip_addresses()) 
      {
        if (ip.is_set()) {
          it.printf(width, ++line * char_height, font_id, TextAlign::BASELINE_RIGHT, "%s", ip.str().c_str());
        }
      }
      bool button0_state = id(button_0_binary_sensor)->state;
      bool button1_state = id(button_1_binary_sensor)->state;
      bool relay_state = id(relay_0_id)->state;
      bool radar_moving = id(ld2410_0_moving_target_binary_sensor)->state;
      it.printf(5, line * char_height, font_id, TextAlign::BASELINE_LEFT, 
        "%s %s %s %s",
        button0_state ? "B0" : "  ",
        button1_state ? "B1" : "  ",
        relay_state ? "R" : " ",
        radar_moving ? "M" : " ");

      auto radar_target = id(ld2410_0_moving_target_binary_sensor);
      if (radar_target->state)
      {
        // motion detected: play the current animation frame and advance the frame
        auto ani = id(motion_detected_animation_id);
        it.image(0, 44, ani, COLOR_ON, COLOR_OFF);
        ani->next_frame();
      }
      else 
      {
        // no motion detected: show the standing still icon
        it.image(0, 44, id(standing_still_icon_id)); 
      }

      float temp = id(bmp_temperature_sensor)->state;
      temp = temp * 1.8 + 32;
      font_id = id(temperature_large_font);
      it.printf(width - 15, height, font_id, TextAlign::BASELINE_RIGHT, "%02.0f", truncf(temp));
      // dunno if I like the decimal point...
      // it.filled_rectangle(width - 18, 43, 3, 3, COLOR_ON); 
      font_id = id(temperature_small_font);
      it.printf(width, 25, font_id, TextAlign::TOP_RIGHT, "%1d", (int)(temp * 10) % 10);



uart:
  id: uart_0
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 57600 
  parity: NONE
  stop_bits: 1

ld2410:
  uart_id: uart_0
  id: ld2410_0

binary_sensor:
  - platform: gpio
    name: "button_0"
    id: button_0_binary_sensor
    pin:
      number: 3
      mode:
        input: true
        pulldown: true
    on_multi_click:
    - timing:
        - ON for at most 0.75s
        - OFF for at most 0.3s
        - ON for at most 0.75s
        - OFF for at least 0.1s
      then:
        - logger.log: "Double Clicked"
    - timing:
        - ON for 0.75s to 3s
        - OFF for at least 0.1s
      then:
        - logger.log: "Single Long Clicked"
    - timing:
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - logger.log: "Single Short Clicked"
      invalid_cooldown: 0.5s
  - platform: gpio
    name: button_1
    id: button_1_binary_sensor
    pin:
      number: 10
      mode:
        input: true
        pulldown: true
    on_multi_click:
    - timing:
        - ON for at most 0.75s
        - OFF for at most 0.3s
        - ON for at most 0.75s
        - OFF for at least 0.1s
      then:
        - logger.log: "Double Clicked"
    - timing:
        - ON for 0.75s to 3s
        - OFF for at least 0.1s
      then:
        - logger.log: "Single Long Clicked"
    - timing:
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - logger.log: "Single Short Clicked"
      invalid_cooldown: 0.5s
  - platform: ld2410
    ld2410_id: ld2410_0
    has_target:
      id: ld2410_0_target_binary_sensor
      name: "Radar Has Target"
    has_moving_target:
      # this changes immediately on motion detection.
      id: ld2410_0_moving_target_binary_sensor
      name: "Radar Moving Target"
    has_still_target:
      # "If true a still target is detected"
      id: ld2410_0_still_target_binary_sensor
      name: "Radar Still Target"

switch:
  - platform: ld2410
    ld2410_id: ld2410_0
    engineering_mode:
      name: "Radar Enable Engineering Mode"
    bluetooth:
      name: "Radar Enable Bluetooth"
  - platform: gpio
    name: "Relay 0"
    id: relay_0_id
    pin: GPIO9

button:
  - platform: ld2410
    ld2410_id: ld2410_0
    factory_reset:
      name: "Radar Factory Reset"
    restart:
      name: "Radar Restart"
    query_params:
      name: "Radar Query Params"
  - platform: restart
    name: "Restart Sensor Device"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WiFi IP"
    ssid:
      name: "WiFi SSID"
    bssid:
      name: "WiFi BSSID"
    mac_address:
      name: "WiFi MAC"
    dns_address:
      name: "WiFi DNS Server"
  - platform: ld2410
    ld2410_id: ld2410_0
    version:
      name: "Radar Firmware Ver"
    mac_address:
      name: "Radar BT MAC"
  # when wired, I suppose this is the thing to replace wifi_info
  # - platform: ethernet_info
  #   ip_address:
  #     name: ESP IP Address
  #     address_0:
  #       name: ESP IP Address 0
  #     address_1:
  #       name: ESP IP Address 1
  #     address_2:
  #       name: ESP IP Address 2
  #     address_3:
  #       name: ESP IP Address 3
  #     address_4:
  #       name: ESP IP Address 4
  #   dns_address:
  #     name: ESP DNS Address
  #   mac_address:
  #     name: ESP MAC Address

sensor:
  - platform: adc
    pin: GPIO2
    name: "Illuminance"
    device_class: illuminance
    unit_of_measurement: lx
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
  - platform: bmp280
    address: 0x77
    # update_interval: 60s
    temperature:
      name: "BMP Temperature"
      id: bmp_temperature_sensor
      oversampling: 2x
    pressure:
      name: "Pressure"
  - platform: aht10
    address: 0x38
    variant: aht20
    # update_interval: 60s
    temperature:
      name: "AHT20 Temperature"
      id: aht20_temp
      accuracy_decimals: 1
      # filters:
      # - filter_out: 0.0
      # - median:
      #     window_size: 3
      #     send_every: 3
      #     send_first_at: 1
    humidity:
      name: "Humidity"
      id: aht20_humidity
      accuracy_decimals: 1
      # filters:
      # - filter_out: 0.0
      # - median:
      #     window_size: 3
      #     send_every: 3
      #     send_first_at: 1