esp8266:
  board: nodemcuv2

packages:
  wifi: !include
    file: include/wifi.yaml
  i2c: !include
    file: include/i2c.yaml
    vars:
      i2c_sda_pin: "GPIO12"
      i2c_scl_pin: "GPIO14"
  display: !include 
    file: include/display.yaml

display:
  - id: !extend ssd1306_id
    lambda: |-
      auto width = it.get_width();
      auto height = it.get_height();

      auto font_id = id(spleen_font);
      auto ip_addr = id(ip_address_id)->get_state();
      int char_height = 8;
      int line = 0;
      it.printf(width, ++line * char_height, font_id, TextAlign::BASELINE_RIGHT, "%s", App.get_name().c_str());
      it.printf(width, ++line * char_height, font_id, TextAlign::BASELINE_RIGHT, "%s", ip_addr.c_str());  

# "All Device" baseline stuff here

<<: !include 
  file: include/esp8266-device-baseline.yaml
  vars:
    device_name: "801-wifi"
    device_comment: "esp8266 with built-in display."
    builtin_led_pin: "2"

