esphome:
  name: picow-test

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

network:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "Son-of-pescadonet"
  password: "Patter69Son"

# not avail as of 2024-09-10
# web_server:

output:
  - platform: gpio
    pin:
      number: 32    # builtin LED on the pico-w
      mode: output
    id: LED

interval:
  - interval: 500ms
    then:
      - output.turn_on: LED
      - delay: 250ms
      - output.turn_off: LED
