esphome:
  name: test-esp32c3

esp32:
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "Son-of-pescadonet"
  password: "Patter69Son"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Esp32C3 Fallback Hotspot"
    password: "PJnNb7VRCS3I"

captive_portal:

switch:
  - platform: gpio
    name: "Laser Beam"
    pin: GPIO2