esphome:
  name: wt32
  platformio_options:
    upload_speed: 115200

esp32:
  board: wt32-eth01
# board: esp-wrover-kit
  framework:
    type: arduino

# see https://esphome.io/components/ethernet.html
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16


# Enable logging
logger:
#  level: DEBUG

# Enable Home Assistant API
api:

ota:
  - platform: esphome
    password: ""


web_server:

# this component sync the local gadget to the time of the Home Asst server
time:
  - platform: homeassistant
    id: esptime