esp32:
  board: wemos_d1_mini32

packages:
  blinky: !include
    file: ../include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wired_ethernet: !include
    file: ../include/wired-ethernet.yaml
    vars:
      ethernet_clk_pin: "GPIO18"  
      ethernet_mosi_pin: "GPIO23" 
      ethernet_miso_pin: "GPIO19" 
      ethernet_cs_pin: "GPIO5" 
      ethernet_interrupt_pin: "GPIO26" 
      ethernet_reset_pin: "GPIO4"
  illuminance: !include
    file: include/photoresistor-illuminance.yaml
    vars:
      illuminance_pin: "GPIO39"
  radar_motion: !include
    file: include/HLK-LD2410-radar-motion.yaml
    vars:
      # GPIO1 and 3 are labeled as UART0, but that conflicts with logging
      # 9 andd 10 are labeled as UART1, but that results in a warning that 
      # those pins might be hooked to flash.  So let's try 17 and 16
      uart_2_tx_pin: "GPIO17" 
      uart_2_rx_pin: "GPIO16" 
  i2c: !include
    file: include/i2c.yaml
    vars:
      # datasheet says 21 and 22 are I2C0
      i2c_sda_pin: "GPIO21"
      i2c_scl_pin: "GPIO22"
      i2c_freq: "420kHz"
  temp_humidity: !include
    file: include/BMP280-AHT20-temp-humidity.yaml
  display: !include
    file: include/SDD1306-OLED-display-fast-boards.yaml
  tone_player: !include
    file: ../include/rtttl-player.yaml
    vars:
      buzzer_pin: "GPIO33"


text_sensor:
  - platform: homeassistant
    name: "RingtoneRTTTL"
    id: ringtone_input_id
    internal: true
    entity_id: input_text.buzzer_ringtone
    on_value:
      then:
        - logger.log:
            format: "Playing %s"
            args: ["x.c_str()"]
        - rtttl.play: !lambda |-
            return x.c_str();


# https://esphome.io/components/mcp230xx.html#mcp230xx-i-o-expander

mcp23017:
  - id: 'mcp23017_0_id'
    address: 0x20


# Individual outputs
# switch:
#   - platform: gpio
#     name: "MCP23017 Pin A0"
#     pin:
#       mcp23xxx: mcp23017_hub
#       # Use pin A0
#       number: 0
#       mode:
#         output: true
#       inverted: false

binary_sensor:
  - platform: gpio
    name: "Pin 0"
    id: keypad_button_0_id
    pin:
      mcp23xxx: mcp23017_0_id
      number: 0
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Pin 1"
    pin:
      mcp23xxx: mcp23017_0_id
      number: 1
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Pin 2"
    pin:
      mcp23xxx: mcp23017_0_id
      number: 2
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Pin 3"
    pin:
      mcp23xxx: mcp23017_0_id
      number: 3
      inverted: true
      mode: 
        input: true
        pullup: true
  - platform: gpio
    name: "Pin 4"
    pin:
      mcp23xxx: mcp23017_0_id
      number: 4
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Pin 5"
    pin:
      mcp23xxx: mcp23017_0_id
      number: 5
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Pin 6"
    pin:
      mcp23xxx: mcp23017_0_id
      number: 6
      inverted: true
      mode:
        input: true
        pullup: true
  - platform: gpio
    name: "Pin 7"
    pin:
      mcp23xxx: mcp23017_0_id
      number: 7
      inverted: true
      mode:
        input: true
        pullup: true
      


binary_sensor:
  - platform: gpio
    name: "Door Lock 0 Sensor"
    id: door_sensor_0_id
    device_class: door
    pin:
      number: GPIO25
      mode:
        input: true
        pulldown: true
  - platform: gpio
    name: "Door Sensor 0"
    id: door_sensor_1_id
    device_class: door
    pin:
      number: GPIO12
      mode:
        input: true
        pulldown: true

# "All Device" baseline stuff here

<<: !include 
  file: ../include/esp32-device-baseline.yaml
  vars:
    device_hostname: "924-esphome"
    device_friendly_name: "Arkadia House Keypad (924)"
    device_comment: "Wherever you go, there you are."
