esphome:
  name: ${device_name}
  friendly_name: ${device_name} 
  comment: ${device_comment}
  name_add_mac_suffix: true
  project:
    name: "arkadiahouse.home_automation"
    version: "0.1.1"

# Enable logging
logger:
  level: DEBUG
  # this will disable serial logging (API access should still work, tho)
  # baud_rate:0 

# Enable Home Assistant API
api:
  password: ""
  # reboot_timeout set to 0s will keep the board running even when networking (connection to the home asst api)
  # is lost, even if lost forever. 
  # reboot_timeout: 0s

ota:
  - platform: esphome
    password: !secret ota_password
      
web_server:
  port: 80

# this component sync the local gadget to the time of the Home Asst server
time:
  - platform: homeassistant
    id: esptime

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "Safely Restart Device"
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: Uptime (approx)
    id: sys_uptime_id
    state_class: total_increasing
    update_interval: 60s
    entity_category: "diagnostic"

