i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  # goose up the i2c bus frequency so that we don't get runtime warnings about the display component
  # taking too long to update.
  frequency: 420kHz
