sensor:
    # https://devices.esphome.io/devices/temt6000
  - platform: adc
    pin: ${illuminance_pin}
    name: "Illuminance"
    device_class: illuminance
    unit_of_measurement: lx
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
    # https://community.home-assistant.io/t/aht20-bmp280-combined-sensor/366411
  - platform: bmp280_i2c
    address: 0x77
    # update_interval: 60s
    # the irr_filter supposedly lowers noise at the expense of power consumption.
    # We don't care about power consumption (for wired devices), so max out the filter.
    iir_filter: 16x
    temperature:
      name: "BMP Temperature"
      id: bmp_temperature_sensor
      oversampling: 2x
    pressure:
      name: "Pressure"
      oversampling: 16x
  - platform: aht10
    address: 0x38
    variant: aht20
    # update_interval: 60s
    temperature:
      name: "AHT20 Temperature"
      id: aht20_temp
      accuracy_decimals: 1
      # filters:
      # - filter_out: 0.0
      # - median:
      #     window_size: 3
      #     send_every: 3
      #     send_first_at: 1
    humidity:
      name: "Humidity"
      id: aht20_humidity
      accuracy_decimals: 1
      # filters:
      # - filter_out: 0.0
      # - median:
      #     window_size: 3
      #     send_every: 3
      #     send_first_at: 1

