substitutions:
  invert_relay_0_pin: "false"

# https://wiki.seeedstudio.com/Grove-Relay/
switch:
  - platform: gpio
    name: "Relay 0"
    id: relay_0_id
    pin: 
      number: ${relay_0_pin}
      inverted: ${invert_relay_0_pin}
      mode:
        output: true
        pulldown: ! ${invert_relay_0_pin}
        pullup: ${invert_relay_0_pin}