esp32:
  board: wt32-eth01
  cpu_frequency: 240MHZ
  framework:
    type: arduino

packages:
  diagnostics: !include 
    file: ../include/diagnostics.yaml

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  # clk_mode: GPIO0_OUT
  clk_mode: GPIO0_IN  
  phy_addr: 1
  power_pin: GPIO16
  
# "All Device" baseline stuff here

<<: !include 
  file: ../include/esp32-device-baseline.yaml
  vars:
    device_hostname: "701-esphome"
    device_friendly_name: "701-esphome"
    device_comment: "Basic config for board 701 connected on wired ethernet."



