esp32:
  board: lolin_s2_mini
  variant: ESP32S2

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO15"
  wifi: !include  
    file: include/wifi.yaml


 

      ethernet_clk_pin: "GPIO35"  
      ethernet_mosi_pin: "GPIO33" 
      ethernet_miso_pin: "GPIO1" 
      ethernet_cs_pin: "GPIO37" 
      ethernet_interrupt_pin: "GPIO39" 
      ethernet_reset_pin: "GPIO2"







color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%

spi:
  interface: hardware
  clk_pin: GPIO18
  mosi_pin: GPIO33


# display D106
display:
  - platform: ili9xxx
    id: display_0_id
    model: ST7789V
    dc_pin: GPIO25
    reset_pin: GPIO26
    cs_pin: GPIO21
    data_rate: 80MHz
    invert_colors: false
    color_palette: NONE
    color_order: bgr
    rotation: 180
    show_test_card: true
    update_interval: 0.5s
    lambda: |-
      static int width = it.get_width();
      static int height = it.get_height();
      static auto color = id(my_red);
      auto touch = id(touchscreen_0_id)->get_touch();
      if (touch) 
      {
        it.filled_circle(touch.value().x, touch.value().y, 10, color);
      }

      static const int NUM_BLINKIES = 3;
      static const int MIN_X = 0;
      static const int MAX_X = width;
      static const int MIN_Y = 0;
      static const int MAX_Y = height;
      static int blinky_x[] = {0, 30, 10, 75};
      static int blinky_y[] = {0, 5, 127, 30};
      static int blinky_dx[] = {1, 1, -2, -3};
      static int blinky_dy[] = {1, -2, 1, 1};
      for (int i = 0; i < NUM_BLINKIES; ++i) 
      {
        blinky_x[i] += blinky_dx[i];
        blinky_y[i] += blinky_dy[i];
        if (blinky_x[i] > MAX_X) { blinky_x[i] = MAX_X;  blinky_dx[i] = -blinky_dx[i]; }
        if (blinky_y[i] > MAX_Y) { blinky_y[i] = MAX_Y;  blinky_dy[i] = -blinky_dy[i]; }
        if (blinky_x[i] < MIN_X ) { blinky_x[i] = MIN_X; blinky_dx[i] = -blinky_dx[i]; }
        if (blinky_y[i] < MIN_Y ) { blinky_y[i] = MIN_Y; blinky_dy[i] = -blinky_dy[i]; }
      }
      for (int i = 0; i < NUM_BLINKIES; ++i)
      {

        if (NUM_BLINKIES - 1 == i) 
        {
          it.line(blinky_x[i], blinky_y[i], blinky_x[0], blinky_y[0], color);
          break;
        }
        it.line(blinky_x[i], blinky_y[i], blinky_x[i + 1], blinky_y[i + 1], color);

      //  it.draw_pixel_at(blinky_x[i], blinky_y[i], COLOR_ON);
      }




# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_hostname: "913-esphome"
    device_comment: "Baseline for board 913."

