esp32:
  board: lolin_s2_mini
  variant: ESP32S2

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO15"
# wifi: !include  
#   file: include/wifi.yaml
  wired_ethernet: !include
    file: include/wired-ethernet.yaml
    vars:
      ethernet_clk_pin: "GPIO34"  
      ethernet_mosi_pin: "GPIO36" 
      ethernet_miso_pin: "GPIO11" 
      ethernet_cs_pin: "GPIO21" 
      ethernet_interrupt_pin: "GPIO16" 
      ethernet_reset_pin: "GPIO9"

# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_hostname: "916-esphome"
    device_comment: "Baseline for board 916."

