esp32:
  board: wemos_d1_mini32
  cpu_frequency: 240MHZ
  framework:
    type: arduino

packages:
  diagnostics: !include 
    file: ../include/diagnostics.yaml
  blinky: !include
    file: ../include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  illuminance: !include
    file: ../include/photoresistor-illuminance.yaml
    vars:
      illuminance_pin: "GPIO39"
  radar_0: !include
    file: ../include/HLK-LD2410-radar-motion.yaml
    vars:
      uart_id: "uart_1"
      radar_id: "ld2410_0"
      uart_tx_pin: "GPIO17" 
      uart_rx_pin: "GPIO16" 
  i2c: !include
    file: ../include/i2c.yaml
    vars:
      # datasheet says 21 and 22 are I2C0
      #
      i2c_sda_pin: "GPIO21"
      i2c_scl_pin: "GPIO22"
      i2c_freq: "420kHz"
  temp_humidity: !include
    file: ../include/BMP280-AHT20-temp-humidity.yaml
    vars: 
      temperature_offset: "0"
  display: !include
    file: ../include/SDD1306-OLED-display-fast-boards.yaml
  wifi: !include
    file: ../include/wifi.yaml
  relay: !include
    file: ../include/single-flarp-relay.yaml









binary_sensor:
  - platform: gpio
    name: "Relay Toggle Button"
    id: button_0_id
    pin:
      number: GPIO15
      mode:
        input: true
        pulldown: true
    on_click:
      min_length: 10ms
      max_length: 1500ms
      then:
        - switch.toggle: relay_0_id

# "All Device" baseline stuff here

<<: !include 
  file: ../include/esp32-device-baseline.yaml
  vars:
    device_hostname: "m-hal-w-f1b1a8-930"
    device_friendly_name: "Gym Hallway West Sensor Unit"
    device_comment: "Retrofit sensor unit on board 930."
