sensor:
  - platform: adc
    # this needs to be an analog input pin
    pin: ${illuminance_pin}
    name: "Photoresistor 0"
    id: illuminance_id
    unit_of_measurement: mV
    attenuation: auto
    update_interval: 10s
    filters:
      - multiply: 100
      - delta: 5.0
