font:
  - file: "fonts/spleen-5x8.bdf"
    id: tiny_font_id
  - file: "fonts/BebasNeue-Regular.ttf"
    id: large_font_id
    size: 68
  - file: "fonts/BebasNeue-Regular.ttf"
    id: small_font_id
    size: 34
  - file: "fonts/BebasNeue-Regular.ttf"
    id: med_font_id
    size: 28

display:
  - platform: ssd1306_i2c
    id: ssd1306_id
    model: "SSD1306_128x64"
    update_interval: 0.2s
    contrast: 20%
    invert: false
    lambda: |-
      static auto width = it.get_width();
      static auto height = it.get_height();
      static auto tiny_font = id(tiny_font_id);
      static auto big_font = id(large_font_id);
      static auto small_font = id(small_font_id);
      static auto med_font = id(med_font_id);
      static const int char_height = 8;
      int line = 0;

      auto ip_addr = id(ip_address_id)->get_state();
      it.printf(width, ++line * char_height, tiny_font, TextAlign::BASELINE_RIGHT, "%s", App.get_name().c_str());
      it.printf(width, ++line * char_height, tiny_font, TextAlign::BASELINE_RIGHT, "%s", ip_addr.c_str());
      

# /*
# bool button0_state = id(button_0_binary_sensor_id)->state;
# bool button1_state = id(button_1_binary_sensor_id)->state;
# bool relay_state = id(relay_0_id)->state;
# bool radar_moving = false; // id(ld2410_0_moving_target_binary_sensor)->state;
# it.printf(0, 1 * char_height, tiny_font, TextAlign::BASELINE_LEFT, 
#   "%s%s",
#   button0_state ? "B" : " ",
#   relay_state ? "R" : " ");
# it.printf(0, 2 * char_height, tiny_font, TextAlign::BASELINE_LEFT, 
#   "%s%s",
#   button1_state ? "b" : " ",
#   radar_moving ? "M" : " ");
# */

# // blinky routine as an array of connected points.
# /*
# static const int NUM_BLINKIES = 3;
# static const int MIN_X = 10;
# static const int MAX_X = 62;
# static const int MIN_Y = 0;
# static const int MAX_Y = 15;
# static int blinky_x[] = {0, 30, 10, 75};
# static int blinky_y[] = {0, 5, 127, 30};
# static int blinky_dx[] = {1, 1, -2, -3};
# static int blinky_dy[] = {1, -2, 1, 1};
# for (int i = 0; i < NUM_BLINKIES; ++i) 
# {
#   blinky_x[i] += blinky_dx[i];
#   blinky_y[i] += blinky_dy[i];
#   if (blinky_x[i] > MAX_X) { blinky_x[i] = MAX_X;  blinky_dx[i] = -blinky_dx[i]; }
#   if (blinky_y[i] > MAX_Y) { blinky_y[i] = MAX_Y;  blinky_dy[i] = -blinky_dy[i]; }
#   if (blinky_x[i] < MIN_X ) { blinky_x[i] = MIN_X; blinky_dx[i] = -blinky_dx[i]; }
#   if (blinky_y[i] < MIN_Y ) { blinky_y[i] = MIN_Y; blinky_dy[i] = -blinky_dy[i]; }
# }
# for (int i = 0; i < NUM_BLINKIES; ++i)
# {
#   if (NUM_BLINKIES - 1 == i) 
#   {
#     it.line(blinky_x[i], blinky_y[i], blinky_x[0], blinky_y[0], COLOR_ON);
#     break;
#   }
#   it.line(blinky_x[i], blinky_y[i], blinky_x[i + 1], blinky_y[i + 1], COLOR_ON);

# //  it.draw_pixel_at(blinky_x[i], blinky_y[i], COLOR_ON);
# }
# */

# float temp = id(temperature_id)->state;
# temp = temp * 1.8 + 32;
# float hum = id(humidity_id)->state;
# float lux = id(illuminance_id)->state;

# it.printf(0, 3 * char_height, tiny_font, TextAlign::BASELINE_LEFT, "%2.1f %2.1f %2.0f", temp, hum, lux);


# /*
# it.printf(0, height, big_font, TextAlign::BASELINE_LEFT, "%2.0f", truncf(temp));
# it.printf(57, 17, tiny_font, TextAlign::TOP_LEFT, "F");
# // dunno if I like the decimal point...
# it.filled_rectangle(54, height - 9, 3, 3, COLOR_ON); 
# // or the fractional temp.
# it.printf(57, (height - 9) / 2, small_font, TextAlign::TOP_LEFT, "%1d", (int)(temp * 10) % 10);

# it.printf(width, 12, med_font, TextAlign::TOP_RIGHT, "%2.1f  ", hum);
# it.printf(width, 24, tiny_font, TextAlign::TOP_RIGHT, "%%");

# it.printf(width, height, med_font, TextAlign::BASELINE_RIGHT, "%2.0f  ", lux);
# it.printf(width, height - char_height, tiny_font, TextAlign::BASELINE_RIGHT, "l"); 
# it.printf(width, height, tiny_font, TextAlign::BASELINE_RIGHT, "x"); 
# */

