esp32:
  board: nodemcu-32s
  cpu_frequency: 240MHZ
  framework:
    type: arduino

packages:
  diagnostics: !include 
    file: ../include/diagnostics.yaml
  wifi: !include
    file: ../include/wifi.yaml
  relay: !include 
    file: ../include/single-relay.yaml
    vars: 
      relay_0_pin: "GPIO4"

binary_sensor:
  - platform: gpio
    name: "Relay Toggle Button"
    id: button_0_id
    pin:
      number: GPIO5
      mode:
        input: true
        pullup: true
    filters:
      - invert:
    on_click:
      min_length: 10ms
      max_length: 1000ms
      then:
        - switch.toggle: relay_0_id

<<: !include 
  file: ../include/esp32-device-baseline.yaml
  vars:
    device_hostname: "m-pat-fence-aaeed4-902"
    device_friendly_name: "Fenceline Lights"
    device_comment: "Single relay with override button. Installed at outdoor kitchen to control fenceline lights."

