esp32:
  board: nodemcu-32s

packages:
  blinky: !include
    file: ../include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  illuminance: !include
    file: ../include/photoresistor-illuminance.yaml
    vars:
      illuminance_pin: "GPIO39"
  radar_motion: !include
    file: ../include/HLK-LD2410-radar-motion.yaml
    vars:
      # GPIO1 and 3 are labeled as UART0, but that conflicts with logging
      # 9 andd 10 are labeled as UART1, but that results in a warning that 
      # those pins might be hooked to flash.  So let's try 17 and 16
      uart_2_tx_pin: "GPIO17"
      uart_2_rx_pin: "GPIO16"
  i2c: !include
    file: ../include/i2c.yaml
    vars:
      # the pinouts for this board say nothing about I2C,
      # but other boards with the same MCU chip use 21 and 22
      i2c_sda_pin: "GPIO21"
      i2c_scl_pin: "GPIO22"
      i2c_freq: "420kHz"
  temp_humidity: !include
    file: ../include/BMP280-AHT20-temp-humidity.yaml
    vars: 
      temperature_offset: "-5.50"    
  display: !include
    file: ../include/SDD1306-OLED-display-fast-boards.yaml
  wifi: !include
    file: ../include/wifi.yaml
  relay: !include
    file: ../include/single-flarp-relay.yaml
  button_selector: !include
    file: ../include/scene-selector-button.yaml
    vars:
      button_pin: "GPIO15"
      scene00: "dining_all_off"
      scene01: "dining_1_percent"
      scene02: "dining_25_percent"
      scene03: "dinner_party_sitting"
      scene04: "dining_100_percent"
      scene05: "dining_tv_mode"
      scene06: creepy_dining_room
      scene07: dining_nitelite_mode
      scene10: bright_dining

# "All Device" baseline stuff here

<<: !include 
  file: ../include/esp32-device-baseline.yaml
  vars:
    device_hostname: "m-dng-01da50-903"
    device_comment: "Retrofit sensor unit on board 903."
    device_friendly_name: "Dining Room Sensor Unit"