esp32:
  board: nodemcu-32s
  cpu_frequency: 240MHZ
  framework:
    type: arduino


packages:
  diagnostics: !include 
    file: ../include/diagnostics.yaml
  blinky: !include
    file: ../include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wifi: !include  
    file: ../include/wifi.yaml

switch:
  - platform: gpio
    name: "Relay A-B"
    id: relay_0_id
    pin: 
      number: 13
      inverted: false
      mode:
        output: true
        pulldown: true

# "All Device" baseline stuff here

<<: !include 
  file: ../include/esp32-device-baseline.yaml
  vars:
    device_hostname: "m-liv-a-b-switch-aa91d4-906"
    device_friendly_name: "Living Room Amp A-B switch"
    device_comment: "A-B selector for stereo speaker input."

