esp32:
  # esp32-WROOM-32.  Waaay overkill for this application...
  board: nodemcu-32s

packages:
  blinky: !include
    file: include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wifi: !include  
    file: include/wifi.yaml

switch:
  - platform: gpio
    name: "Relay A-B"
    id: relay_0_id
    pin: 
      number: 13
      inverted: false
      mode:
        output: true
        pulldown: true

# "All Device" baseline stuff here

<<: !include 
  file: include/esp32-device-baseline.yaml
  vars:
    device_hostname: "906-a-b-stereo-switch"
    device_comment: "A-B selector for stereo speaker input."

